config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'

  resources :rooms do
    resources :tweets do
      resource :like
      resource :retweet
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :tweets

  after_create_commit { broadcast_prepend_to :rooms }
  after_update_commit { broadcast_replace_to :tweets }
  after_destroy_commit { broadcast_remove_to :tweets }

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  after_create_commit :broadcast_to_room
  after_create_commit { broadcast_prepend_to :tweets }
  after_update_commit { broadcast_replace_to :tweets }
  after_destroy_commit { broadcast_remove_to :tweets }

  belongs_to :room

  has_many_attached :images
  has_rich_text :content

  private

  def broadcast_to_room
    room = self.room
    broadcast_append_to "room-#{room.id}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_tweet

  def create
    @tweet.increment! :likes_count
    redirect_to @tweet
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all.order(created_at: :desc)
    @room = Room.new
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @tweets = @room.tweets
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  def create
    room_id = { room_id: params[:room_id] }
    merged_params = tweet_params.merge(room_id)
    @tweet = Tweet.new(merged_params)
    @tweet.save

    # respond_to do |format|
    #   if @tweet.save
    #     format.html { redirect_to tweets_url, notice: 'Tweet was successfully created.' }
    #   else
    #     format.turbo_stream { render turbo_stream: turbo_stream.replace(@tweet, partial: "tweets/form", locals: { tweet: @tweet }) }
    #     format.html {
    #       render :index
    #     }
    #   end
    # end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweets_path, notice: 'Tweet was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tweet_params
    params.require(:tweet).permit(:body, :content, images: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotrails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
    <%= turbo_include_tags %>
    <%= stimulus_include_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.submit %>
  </div>

<% end %>

app/views/rooms/_room.html.erb
<%= turbo_frame_tag dom_id(room) do %>
  <tr>
    <td><%= room.name %></td>
    <td><%= link_to 'Show', room %></td>
    <td><%= link_to 'Edit', edit_room_path(room) %></td>
    <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<%= turbo_stream_from "rooms" %>
<%= turbo_frame_tag "rooms" do %>
  <%= render @rooms %>
<% end %>

<br>

<%= turbo_frame_tag 'room' do %>
  <%= render 'form', room: @room %>
<% end %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>채팅방 Name:</strong>
  <%= @room.name %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

<br>
<br>

<%= form_with(model: Tweet.new, methods: :post, url: room_tweets_path(@room.id), remote: true) do |f| %>
  <%= f.rich_text_area :content %>
  <br>
  <%= f.submit %>
<% end %>

<br>
<hr>
<br>

<%= turbo_stream_from "room-#{@room.id}" %>
<%= turbo_frame_tag "room-#{@room.id}" do %>
  <%= render @tweets %>
<% end %>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, id: dom_id(tweet)) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div>
    <%= form.file_field :images, multiple: true %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<%= turbo_frame_tag dom_id(tweet) do %>
  <div>
    <td style="font-size: 30px;"><%= tweet.content %></td>

    <span>
      <%#= button_to "쪼아 #{tweet.likes_count}", tweet_like_path(tweet), method: :post, id: 'form' %>
    </span>

    <span>
      <button>
        <%= tweet.retweets_count %>
      </button>
    </span>

    <div>
      <% if tweet.images.attached? %>
        <div>foo</div>
        <% tweet.images.each do |image| %>
          <%= image_tag image %>
        <% end %>
      <% end %>
    </div>

    <%#= link_to 'Show', tweet_path(tweet) %>

    <%#= link_to 'Edit', edit_tweet_path(tweet) %>

    <%#= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<%= turbo_frame_tag dom_id(@tweet) do %>
  <%= render 'form', tweet: @tweet %>
<% end %>

app/views/tweets/index.html.erb
<%= turbo_stream_from "tweets" %>

<%= turbo_frame_tag 'tweet' do %>
  <%= render 'form', tweet: @tweet %>
<% end %>

<%= turbo_frame_tag "tweets" do %>
  <%= render @tweets %>
<% end %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<%= turbo_frame_tag dom_id(@tweet) do %>
  <p>
    <strong>Content:</strong>
    <%= @tweet.content %>
  </p>

  <%= link_to 'Back', tweets_path, "data-turbo-frame": "_top" %>
<% end %>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>